story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),  # nama_app.urls
    path('subject/', include('story5.urls')),
    path('activity/', include('story6.urls')),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    # path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi')
    path('', views.homepage, name='homepage'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.subject, name='subject'),
    path('add/', views.subject_add, name='subject_add'),
    path('detail/<int:index>/', views.subject_detail, name='subject_detail'),
    # path('list/', views.subject, ),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.activity, name='activity'),  # Halaman list kegiatan
    # Halaman form kegiatan
    path('add/', views.activity_add, name='activity_add'),
]

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.


class Subject(models.Model):
    matkul = models.CharField('Subject', max_length=120, null=True)
    dosen = models.CharField('Lecturer', max_length=120, null=True)
    sks = models.IntegerField('Total Credit', null=True)
    semester = models.IntegerField('Semester', null=True)
    kelas = models.CharField('Class', max_length=120, null=True)

    def __str__(self):
        return self.matkul


class Assignment(models.Model):
    matkul = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)
    deskripsi = models.TextField('Description', blank=True)
    deadline = models.DateField('Deadline', null=True)

story6/models.py
from django.db import models

# Create your models here.


class Activity(models.Model):
    kegiatan = models.CharField('Activity', max_length=120, null=True)
    deskripsi = models.TextField('Description', blank=True)
    tanggal = models.DateField('Date', null=True)

    def __str__(self):
        return self.kegiatan


class Participant(models.Model):
    kegiatan = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True)
    nama = models.CharField('Name', max_length=120, null=True)

    def __str__(self):
        return self.nama

story5/forms.py
from django.forms import ModelForm
from .models import Subject, Assignment


class SubjectForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Subject
        fields = '__all__'


class AssignmentForm(ModelForm):
    class Meta:
        ordering = ['deadline']

story6/forms.py
from django.forms import ModelForm
from .models import Activity, Participant


class ActivityForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Activity
        fields = '__all__'


class ParticipantForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Participant
        fields = '__all__'

story4/views.py
from django.shortcuts import render

# Create your views here.


def homepage(request):
    return render(request, 'homepage.html')

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Subject, Assignment
from .forms import SubjectForm
import datetime

# Create your views here.


def subject(request):
    if request.method == "POST":
        Subject.objects.get(id=request.POST['id']).delete()
        return redirect('/subject/')
    subject_list = Subject.objects.all()
    return render(request, 'subject_list.html', {'subject_list': subject_list})


def subject_add(request):
    submit = False
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            # return render(request, 'subject_add.html')
            return HttpResponseRedirect('/subject/add/?submit=True')
    else:
        form = SubjectForm()
        if 'submit' in request.GET:
            submit = True
    return render(request, 'subject_add.html', {'form': form, 'submit': submit})


def subject_detail(request, index):
    subject = Subject.objects.get(pk=index)
    assignment = Assignment.objects.filter(matkul_id=subject)

    today = assignment.filter(deadline__lt=datetime.date.today())
    near = assignment.filter(deadline__range=(
        datetime.date.today(), datetime.date.today() + datetime.timedelta(days=6)))
    far = assignment.filter(
        deadline__gte=datetime.date.today() + datetime.timedelta(days=7))

    tasks = {
        'subject': subject,
        'today': today,
        'near': near,
        'far': far,
    }

    return render(request, 'subject_detail.html', tasks)

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Activity, Participant
from .forms import ActivityForm, ParticipantForm

# Create your views here.

# Nampilin list kegiatan yang ada + peserta yang terdaftar


def activity(request):
    submit = False
    activity_list = Activity.objects.all()
    participant_list = Participant.objects.all()
    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/activity/?submit=True')
    else:
        form = ParticipantForm()
        if 'submit' in request.GET:
            submit = True
    return render(request, 'activity_list.html', {'form': form, 'submit': submit, 'activity_list': activity_list, 'participant_list': participant_list})

# Nampilin form untuk nambah kegiatan


def activity_add(request):
    submit = False
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/activity/add/?submit=True')
    else:
        form = ActivityForm()
        if 'submit' in request.GET:
            submit = True
    return render(request, 'activity_add.html', {'form': form, 'submit': submit})

story4/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block body_main %}
<!-- Landing section -->
<div class="landing text-center">
  <div class="d-flex justify-content-center align-items-center">
    <h1 style="color: #514545;">
      H E <span style="color: #D45D79;">L L </span>O
    </h1>
  </div>
  <div class="d-flex justify-content-center align-items-center">
    <h6 style="color: #514545;">I'M WENING DYAH LOCITARESMI</h6>
  </div>
</div>

<!-- Border -->
<div section="border">
  <div class="row">
    <div class="col-4 border1"></div>
    <div class="col-4 border2"></div>
    <div class="col-4 border3"></div>
  </div>
</div>

<!-- Quote section -->
<div class="quote container justify-content-center align-items-center text-center">
  <h1>"</h1>
  <h5 style="color: #767676;">
    TIME IS TOO SLOW <span style="color: ">FOR THOSE WHO WAIT</span>, TO
    SWIFT <span style="color: black;">FOR THOSE WHO FEAR</span>, TOO LONG
    <span style="color: black;">FOR THOSE WHO GRIEVE</span>, TOO SHORT
    <span style="color: black;">FOR THOSE WHO REJOICE</span>, BUT FOR THOSE
    WHO LOVE, <span style="color: black;">TIME IS ETERNITY</span>
  </h5>
  <br />
  <h1>"</h1>
</div>

<!-- About me section -->
<div class="row">
  <div class="col-lg-4 col-sm-6 container" id="about-me-1">
    <h1 style="font-weight: 700;">About Me</h1>
    <hr>
    <p><span style="font-weight: bold;">Lorem ipsum</span> dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. </p>
  </div>
  </h2>
  <div class="col-lg-4 col-sm-6" id="about-me-2" style="padding: 0;">
    <div class="row" id="b-1" style="background-image: url({% static 'fe-rev.jpg' %})">
    </div>
    <div class="row" id="b-2">
      <p><span style="font-weight: bold;">Lorem ipsum</span> dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
    </div>
  </div>
  <div class="col-lg-4 col-sm-12" id="about-me-3">
    <div class="row" id="c-1">
      <p><span style="font-weight: bold;">Lorem ipsum</span> dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. </p>
    </div>
    <div class="row" id="c-2" style="background-image: url({% static 'manda-rev.jpg' %})"></div>
  </div>
</div>

<!-- Academic section -->
<div class="academic container ">
  <h2 style="margin-bottom: 10vh; text-align: center;">M Y &nbsp; A C A D E M I C &nbsp; P A T H</h2>
  <div class="academic-list">
    <ol class="rectangle-list">
      <li id="bold">Faculty of Computer Science, Universitas Indonesia (2019 - present)
        <ol>
          <li id="un-bold">Human Resource Staff at Pesta Rakyat Komputer 2020</li>
          <li id="un-bold">Human Resource Staff at Compfest 12</li>
        </ol>
      </li>
      <li id="bold">SMAN 2 Kota Tangerang Selatan (2017 - 2019)
        <ol>
          <li id="un-bold">Acceleration program</li>
          <li id="un-bold">Student council officer</li>
        </ol>
      </li>
      <li id="bold">Candle Tree Junior High School (2014 - 2017)
        <ol>
          <li id="un-bold">President of student council</li>
          <li id="un-bold">Silver medal winner, Digital Technologies, ICAS 2016</li>
        </ol>
      </li>
      <li id="bold">Candle Tree Elementary School (2008 - 2014)
        <ol>
          <li id="un-bold">Silver medal winner, Computer Skills, ICAS 2013, 2014</li>
        </ol>
      </li>
    </ol>
  </div>

</div>

<!-- Interests section -->
<div class="interests" style="background-image: url({% static 'band.jpg' %})">
  <div class="container">
    <div class="row justify-content-center mb-5">
      <h1 style="color: white; text-align: center;">W H A T &nbsp; I ' M &nbsp;<span style="color: #D45D79;">I N T E R E
          S T E D</span> &nbsp; A T</h1>
    </div>
    <div class="row pt-4">
      <div class="col-6">
        <hr align="right" id="hr-1"><br>
        <hr align="right" id="hr-2"><br>
        <hr align="right" id="hr-3">
      </div>
      <div class="col-6" style="padding-top: 12px;">
        <h4 style="margin-bottom: 19px;">Music</h4><br>
        <h4 style="margin-bottom: 19px;">Information technology</h4><br>
        <h4>Graphic design</h4>
      </div>
    </div>
  </div>
</div>

<!-- Portfolio section -->
<div class="portfolio text-center">
  <h1>PORTFOLIO</h1>
  <h5 style="font-weight: bold; margin-bottom: 15vh;">HERE IS A LIST OF THINGS THAT I HAVE DONE THOROUGH MY STUDY</h5>
  <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-1">
    <div class="col content" id="p-item">
      <div class="content-overlay"></div>
      <img src="{% static 'p1.jpg' %}" alt="" srcset="">
      <div class="content-details fadeIn-bottom">
        <h3 class="content-title">Project Name</h3>
        <p class="content-text">A short description</p>
      </div>
    </div>
    <div class="col content" id="p-item">
      <div class="content-overlay"></div>
      <img src="{% static 'p2.jpg' %}" alt="" srcset="">
      <div class="content-details fadeIn-bottom">
        <h3 class="content-title">Project Name</h3>
        <p class="content-text">A short description</p>
      </div>
    </div>
    <div class="col content" id="p-item">
      <div class="content-overlay"></div>
      <img src="{% static 'p3.jpg' %}" alt="" srcset="">
      <div class="content-details fadeIn-bottom">
        <h3 class="content-title">Project Name</h3>
        <p class="content-text">A short description</p>
      </div>
    </div>
    <div class="col content" id="p-item">
      <div class="content-overlay"></div>
      <img src="{% static 'p4.jpg' %}" alt="" srcset="">
      <div class="content-details fadeIn-bottom">
        <h3 class="content-title">Project Name</h3>
        <p class="content-text">A short description</p>
      </div>
    </div>
    <div class="col content" id="p-item">
      <div class="content-overlay"></div>
      <img src="{% static 'p5.jpg' %}" alt="" srcset="">
      <div class="content-details fadeIn-bottom">
        <h3 class="content-title">Project Name</h3>
        <p class="content-text">A short description</p>
      </div>
    </div>
    <div class="col content" id="p-item">
      <div class="content-overlay"></div>
      <img src="{% static 'p6.jpg' %}" alt="" srcset="">
      <div class="content-details fadeIn-bottom">
        <h3 class="content-title">Project Name</h3>
        <p class="content-text">A short description</p>
      </div>
    </div>
  </div>

</div>

<!-- Contact section -->
<div class="contact">
  <div class="container text-center">
    <h5>LOOKS LIKE YOU'VE REACHED THE END OF THE PAGE.<br>
      IF YOU WANT TO TALK WITH ME, YOU CAN FIND ME<br>
      ON MY SOCIAL MEDIAS</h5><br>
    <h5>YOU CAN ALSO MAIL ME <a href="https://mail.google.com/mail/?view=cm&fs=1&to=weninglc@gmail.com" target="_blank"
        style="color: #BC5090;">HERE</a>!</h5>
    <br><br>
    <a href="https://www.linkedin.com/in/weningdyahlocitaresmi/" target="_blank">
      <img src="{% static 'Linkedin.png' %}" alt="">
    </a>
    <a href="https://www.instagram.com/weninglc/" target="_blank">
      <img src="{% static 'Instagram.png' %}" alt="">
    </a>
    <a href="https://github.com/weninglc" target="_blank">
      <img src="{% static 'Github.png' %}" alt="">
    </a><br><br><br>
    <p>C O D E D &nbsp; W I T H &nbsp; 💖 &nbsp; B Y &nbsp; M E</p>
  </div>
</div>

<!-- Another border -->
<div section="border">
  <div class="row">
    <div class="col-4 border1"></div>
    <div class="col-4 border2"></div>
    <div class="col-4 border4"></div>
  </div>
</div>
{% endblock %}

story5/templates/subject_add.html
{% extends "base.html" %} {% load static %} {% block body_main %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
  {% if submit %}
  <div class="success p-5 col-12 text-center">
    Successfully added a subject.
  </div>
  <button class="btn btn-primary d-flex m-auto click">
    <a href="{% url 'story5:subject_add' %}" class="text-white">
      Back
    </a>
  </button>
  {% else %}
  <div class="section-title mx-auto text-center p-5">
    <h1>Add A Subject</h1>
  </div>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    <table class="table mx-5 " style="width:90vw">
      {{ form.as_table }}
      <tr>
        <td>&nbsp;</td>
        <td>
          <input type="submit" value="Submit" class="btn btn-primary click" />
        </td>
      </tr>
    </table>
  </form>
</section>
{% endif %} {% endblock %}

story5/templates/subject_detail.html
{% extends "base.html" %} {% load static %} {% block body_main %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
  <div class="section-title m-auto text-center p-5">
    <h1>{{ subject.matkul }}</h1>
  </div>
  <table class="table table-bordered mx-5" style="width:90vw;">
    <tbody>
      <tr>
        <td><b>Lecturer</b></td>
        <td>{{ subject.dosen }}</td>
      </tr>

      <tr>
        <td><b>Total Credit</b></td>
        <td>{{ subject.sks }}</td>
      </tr>

      <tr>
        <td><b>Semester</b></td>
        <td>{{ subject.semester }}</td>
      </tr>

      <tr>
        <td><b>Class</b></td>
        <td>{{ subject.kelas }}</td>
      </tr>
    </tbody>
  </table>
  <table class="table table-bordered mx-5" style="width:90vw">
    <tr>
      <td class="text-center" colspan="2"><b> Tasks </b></td>
    </tr>
    {% for x in today %}
    <tr class="table-danger">
      <td>{{ x.deskripsi }}</td>
      <td>{{ x.deadline }}</td>
    </tr>
    {% endfor %} {% for x in near %}
    <tr class="table-warning">
      <td>{{ x.deskripsi }}</td>
      <td>{{ x.deadline }}</td>
    </tr>
    {% endfor %} {% for x in far %}
    <tr class="table-info">
      <td>{{ x.deskripsi }}</td>
      <td>{{ x.deadline }}</td>
    </tr>
    {% endfor %}
  </table>

  <button class="btn btn-primary d-flex m-auto click">
    <a href="{% url 'story5:subject' %}" class="text-white">
      Back
    </a>
  </button>
</section>
{% endblock %}

story5/templates/subject_list.html
{% extends "base.html" %} {% load static %} {% block body_main %}
<section class="container-fluid d-flex flex-wrap align-content-center mb-5">
  <div class="section-title mx-auto text-center p-5">
    <h1>My Subjects</h1>
  </div>
  <table class="table table-bordered table-hover mx-5 mb-5" style="width:90vw">
    <thead class="thead-light text-center">
      <tr>
        <th>Subject</th>
        <th>Lecturer</th>
        <th>Total Credit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for x in subject_list %}
      <tr>
        <td><a href="detail/{{ x.id }}">{{ x.matkul }} </a></td>
        <td>{{ x.dosen }}</td>
        <td class="text-center">{{ x.sks }}</td>
        <td class="text-center">
          <form method="POST" action="{% url 'story5:subject' %}">
            {% csrf_token %}
            <input name="id" value="{{x.id}}" type="hidden" />
            <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2" style="font-size: 0.8rem;">
              Delete
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <button class="btn btn-primary d-flex m-auto click">
    <a href="{% url 'story5:subject_add' %}" class="text-white">
      Add a new subject
    </a>
  </button>
</section>

{% endblock %}

story6/templates/activity_add.html
{% extends "base.html" %} {% load static %} {% block body_main %}
<section class="container-fluid d-flex flex-wrap align-content-center ">

  <div class="section-title mx-auto text-center p-5">
    <h1>Add An Activity</h1>
  </div>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    <table class="table mx-5" style="width:90vw">
      {{ form.as_table }}
      {% if submit %}
      <tr>
        <td>&nbsp;</td>
        <td>Successfully added an activity.</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>
          <button class="btn btn-primary d-flex  click">
            <a href="{% url 'story6:activity_add' %}" class="text-white">
              Add another activity
            </a>
          </button>
        </td>
      </tr>
      {% else %}
      <tr>
        <td>&nbsp;</td>
        <td>
          <input type="submit" value="Submit" class="btn btn-primary click" />
        </td>
      </tr>
      {% endif %}
    </table>
  </form>

</section>
{% endblock %}

story6/templates/activity_list.html
{% extends "base.html" %} {% load static %} {% block body_main %}
<div class="section-title mx-auto text-center p-5">
  <h1>My Activities</h1>
</div>
<table class="table-hover table table-bordered mx-5 mb-5" style="width:90vw">
  <thead class="thead-light text-center">
    <tr>
      <th>Activity</th>
      <th>Date</th>
      <th>Description</th>
      <th>Participant</th>
    </tr>
  </thead>
  <tbody>
    {% for activity in activity_list %}
    <tr>
      <td class="text-center"><b>{{ activity.kegiatan }}</b></td>
      <td class="text-center">{{ activity.tanggal }}</td>
      <td class="text-center">{{ activity.deskripsi }}</td>
      <td>
        {% for participant in participant_list %}
        {% if participant.kegiatan == activity %}
        <ul>
          <li>{{ participant }}</li>
        </ul>
        {% endif %}
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<form action="" method="POST" novalidate>
  {% csrf_token %}

  <table class="table mx-5" style="width:40vw">
    {% if submit %}
    <tr>
      <td>&nbsp;</td>
      <td>Successfully added an activity.</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
        <button class="btn btn-primary d-flex  click">
          <a href="{% url 'story6:activity' %}" class="text-white">
            Register to another activity
          </a>
        </button>
      </td>
    </tr>
    {% else %}
    {{ form.as_table }}
    <tr>
      <td>&nbsp;</td>
      <td>
        <input type="submit" value="Submit" class="btn btn-primary click" />
      </td>
    </tr>
    {% endif %}
  </table>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Wening Dyah Locitaresmi</title>
    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}" />
  </head>

  <body>
    {% include 'navbar.html' %} {% block body_main %} {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

templates/navbar.html
<div class="dropdown fixed-top mt-4">
  <button class="btn btn-secondary dropdown-toggle ml-4 pl-3 pr-3 bg-light text-dark" type="button" id="dropdownMenu1"
    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'story4:homepage' %}">Home</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'story5:subject' %}">Subjects I'm In</a>
    <a class="dropdown-item" href="{% url 'story5:subject_add' %}">Add A Subject</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'story6:activity' %}">My Activities</a>
    <a class="dropdown-item" href="{% url 'story6:activity_add' %}">Add An Activity</a>
  </div>
</div>